#!/bin/env python3
"""
gpas-uploaded script
"""

import argparse

parser = argparse.ArgumentParser(description="gpas sequencing data upload tool")
parser.add_argument("--json", action="store_true", default=False)

submit_args = subargs.add_parser("submit")
submit_args.add_argument("ticket")

import_args = subargs.add_parser("import")
import_args.add_argument("samplesheet")
import_args.add_argument("--dir", default=None)

if __name__ == "__main__":
    args = parser.parse_args()
